import {Dimensions} from 'react-native';
module.exports = {
  container: {
    flex: 1,
    backgroundColor: 'black',
    flexDirection: 'column',
  },
  svgCurve: {
    position: 'absolute',
    width: Dimensions.get('window').width,
  },
  headerText: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#fff',
    textAlign: 'center',
    marginTop: 35,
    alignItems: 'center',
    marginRight: 30,
  },
  loginheaderText: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#fff',
    textAlign: 'center',
    marginTop: 35,
    alignItems: 'center',
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  welcometxt: {
    fontSize: 20,
    fontWeight: '700',
    color: 'white',
  },
  textInput: {
    width: '90%',
    padding: 10,
    backgroundColor: '#eeeeee',
    borderRadius: 20,
    paddingHorizontal: 16,
    fontSize: 16,
    color: '#002f6c',
    marginVertical: 10,
  },
  button: {
    width: 300,
    backgroundColor: '#4f83cc',
    borderRadius: 25,
    marginVertical: 10,
    paddingVertical: 12,
  },
  buttonText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#ffffff',
    textAlign: 'center',
  },
  text: {
    color: '#c0c0c0',
    fontWeight: 'bold',
  },
  forgotpasstxt: {
    color: '#c0c0c0',
    fontWeight: 'bold',
  },
  svgCurvefooter: {
    position: 'relative',
    bottom: 0,
    width: Dimensions.get('window').width,
    left: 270,
    //top: 260,
    top: 160,
    // top: 130,
  },
  containerFull: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
    backgroundColor: 'black',
    paddingVertical: 50,
  },
  goback: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#fff',
    textAlign: 'center',
    marginTop: 35,
    right: 80,
  },
  formHead: {
    color: '#c0c0c0',
    //color: 'black',
    fontWeight: '700',
    //marginBottom: 30,
  },
  formHead3: {
    fontSize: 25,
    color: 'white',
    textAlign: 'center',
    fontWeight: 'bold',
    // padding: 10,
    // borderRadius: 10,
    // width: '80%',
    // marginVertical: 10,
  },
  icons1: {
    color: 'white',
    fontSize: 30,
  },
  searchbar: {
    width: '90%',
    backgroundColor: 'white',
    borderRadius: 30,
    paddingVertical: 10,
    paddingHorizontal: 20,
    marginTop: 20,
    fontSize: 18,
    //alignItems: 'center',
    //alignSelf: 'center',
  },
};
